import Config

# Configure your database
config :cortex, Cortex.Repo,
  database: Path.expand("../cortex_dev.db", __DIR__),
  pool_size: 5,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :cortex, CortexWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: String.to_integer(System.get_env("PORT") || "5002")],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "oudm+9RzJK8wDEacvCEVXd8nvs6pmFf62ClNq6IoXK5P2qPeyD1wQ3rrSu0q9JAF",
  watchers: [
    bun: ["run", "dev", cd: Path.expand("../assets", __DIR__)]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :cortex, CortexWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/cortex_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :cortex, dev_routes: true

# 在开发环境中覆盖为不要求管理员验证（编译时生效）
config :cortex, require_admin: false

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Telegram Bot Configuration
config :cortex, :telegram, bot_token: System.get_env("TELEGRAM_BOT_TOKEN")

# Feishu Bot Configuration
config :cortex, :feishu,
  app_id: System.get_env("FEISHU_APP_ID"),
  app_secret: System.get_env("FEISHU_APP_SECRET"),
  verification_token: System.get_env("FEISHU_VERIFICATION_TOKEN"),
  encrypt_key: System.get_env("FEISHU_ENCRYPT_KEY")
